name: PR Check
on:
  pull_request:
    branches:
      - '*'

jobs:
  check:
    name: Check label
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2.4.0
#      - name: set up JDK 1.11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.11
      - name: Check label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TMP_RESULT=$(gh pr view --json labels --jq ".labels | .[] | select(.name == \"waiting\") | .name")
          exit $((( $(expr length $TMP_RESULT) > 0 )))
