on:
  pull_request:
    branches:
      - '*'

jobs:
  check:
    name: Check label
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Check label
        run: |
          TMP_RESULT=$(gh pr view --json labels --jq ".labels | .[] | select(.name == \"waiting\") | .name")
          exit $((( $(expr length $TMP_RESULT) > 0 )))
